name: Build APK

on:
  push:
    branches:
      - test-floating-keyboard-20260604-225446
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Install build dependencies
        run: |
          sdkmanager --install "cmake;3.31.6"
          sudo apt update
          sudo apt install -y extra-cmake-modules gettext

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build release APK
        run: ./gradlew :app:assembleRelease -PbuildABI=x86_64

      - name: Upload app
        uses: actions/upload-artifact@v6
        with:
          name: app-release
          path: app/build/outputs/apk/release/
